---
- name: Gather Linux System Status Data
  #  hosts: linux_hosts
  hosts: netcfgsvr1.j114.army.mil
  gather_facts: false
  vars:
    ansible_remote_tmp: /var/tmp/ans
    host_key_checking: false
  tasks:
    - name: Check service status
      ansible.builtin.service_facts:
      register: app_check_output

    - name: display installed services and their status
      ansible.builtin.debug:
        var: app_check_output

          #    - name: display installed services and their status
          #      ansible.builtin.debug:
          #        msg: "Service: {{ item.name }}, State: {{ item.state }}"
          #      loop: "{{ app_check_output }}"
          #      loop_control:
          #        label: "Service: {{ item.name }}, State: {{ item.state }}"
