---
- name: Windows Update Availability Check (Optimized)
  hosts: win_hosts
  gather_facts: no
  vars:
    metrics_path: "C:\\metrics\\updates_available.prom"
    
  tasks:
    - name: Check if inventory_hostname is an IP address
      shell: |
        if [[ {{ inventory_hostname }} =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo true
        else
          echo false
        fi
      register: is_ip_address
      changed_when: false
      delegate_to: localhost

    - name: Resolve IP address on control node if not already an IP address
      shell: getent ahostsv4 {{ inventory_hostname }} | head -n 1 | awk '{print $1}'
      register: ip_lookup
      when: not is_ip_address.stdout == 'true'
      delegate_to: localhost

    - name: Set IP address fact
      set_fact:
        host_ip: "{{ inventory_hostname if is_ip_address.stdout == 'true' else ip_lookup.stdout.strip() }}"
      delegate_to: localhost

    - name: Create required directories
      win_file:
        path: "{{ item }}"
        state: directory
      with_items:
        - C:\scripts
        - C:\metrics

    - name: Check for available Windows updates (no install)
      ansible.windows.win_updates:
        category_names: '*'
        state: searched
      register: update_info

    - name: Set facts for metrics
      ansible.builtin.set_fact:
        hostname: "{{ ansible_hostname }}"
        ip_address: "{{ ansible_host }}"
        timestamp: "{{ ansible_date_time.iso8601 }}"
        update_count: "{{ update_info.found_update_count | default(0) }}"
        updates_list: "{{ update_info.updates | default([]) }}"

    - name: Build metrics content
      ansible.builtin.set_fact:
        metrics_content: |
          # HELP windows_updates_available_count Number of available Windows updates
          # TYPE windows_updates_available_count gauge
          windows_updates_available_count{host="{{ hostname }}", ip="{{ ip_address }}", timestamp="{{ timestamp }}"} {{ update_count }}

          # HELP windows_update_available_info Information about available updates
          # TYPE windows_update_available_info gauge
          {% if update_count|int > 0 %}
          {% for guid, u in updates_list.items() %}
          {% set kb = (u.kb[0] if (u.kb | length > 0) else 'N/A') %}
          {% set title = (u.title | string | replace('"', "'") | regex_replace('[,\\n]', ' ')) %}
          windows_update_available_info{host="{{ hostname }}", ip="{{ ip_address }}", kb="KB{{ kb }}", title="{{ title }}", timestamp="{{ timestamp }}"} 1
          {% endfor %}
          {% else %}
          # No updates available
          {% endif %}
          
    - name: Write metrics file
      ansible.windows.win_copy:
        content: "{{ metrics_content }}"
        dest: "{{ metrics_path }}"
        force: yes

    - name: Display summary
      ansible.builtin.debug:
        msg: |
          ✅ {{ hostname }} has {{ update_count }} update(s) available.
          Prometheus metrics written to {{ metrics_path }}.
